version: '3'
services:
  web:
    build: .
    container_name: uploooaad
    ports:
      - '5000:5000'
  mongodb:
    image: 'mongo:latest'
    container_name: uploooaad_mongodb
    ports:
      - '27017:27017'
